---
title: "Darko FPTS Ranker 2024"
author: "Enzo Moraes Mescall"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

## Translate stats into fantasy points

```{r}
# Declare values
fFGM = 2
fFGA = -1
fFTM = 1
fFTA = -1 
f3PM = 1
fREB = 1
fAST = 2
fSTL = 4
fBLK = 4
fTO = -2
fPTS = 1
```

```{r}
# Read data
#darko_box_24 = read.csv("DARKO_daily_projections_2024-06-30.csv")
#darko_pct_24 = read.csv("DARKO_player_talent_2024-06-30.csv")
darko_box_24 = read.csv("DARKO_daily_projections_2024-11-12.csv")
darko_pct_24 = read.csv("DARKO_player_talent_2024-11-12.csv")
```

```{r}
# Combined dataset
darko_full_24 = darko_box_24 %>%
  inner_join(darko_pct_24, by = join_by(Player == Player)) %>%
  mutate(Player = gsub("[[:punct:]]", "", Player)) %>%
  mutate(Player = gsub("^(\\w+\\s+\\w+).*", "\\1", Player)) %>%
  mutate(FGM = FGA * FG2.) %>%
  mutate(FTM = FTA * FT.) %>%
  mutate(FG3M = FG3A * FG3.)  %>%
  mutate(Player = str_trim(Player)) %>%
  select(Player, Minutes, FGM, FGA, FTM, FTA, FG3M, DREB, OREB, AST, STL, BLK, TOV, PTS, Experience.x)
```

```{r}
# go through GET api which downloads csv
darko_box_url = "https://apanalytics.shinyapps.io/DARKO/_w_9c172727/session/6133f34ec34e6506809b60e51aec35df/download/download_daily?w=9c172727"
darko_box_api = read.csv(darko_box_url)
darko_pct_url = "https://apanalytics.shinyapps.io/DARKO/_w_9c172727/session/6133f34ec34e6506809b60e51aec35df/download/download_talent?w=9c172727"
darko_pct_api = read.csv(darko_pct_url)
```

```{r}
darko_full_api = darko_box_api %>%
  inner_join(darko_pct_api, by = join_by(Player == Player)) %>%
  mutate(Player = gsub("[[:punct:]]", "", Player)) %>%
  mutate(Player = gsub("^(\\w+\\s+\\w+).*", "\\1", Player)) %>%
  mutate(FGM = FGA * FG2.) %>%
  mutate(FTM = FTA * FT.) %>%
  mutate(FG3M = FG3A * FG3.)  %>%
  mutate(Player = str_trim(Player)) %>%
  select(Player, Minutes, FGM, FGA, FTM, FTA, FG3M, DREB, OREB, AST, STL, BLK, TOV, PTS, Experience.x)
```


```{r}
darko_fpts_api = darko_full_api %>%
  mutate(DARKO_FPTS = fFGM * FGM + fFGA * FGA + fFTM * FTM + fFTA * FTA +
           f3PM * FG3M + fREB * (DREB + OREB) + fAST * AST + fSTL * STL +
           fBLK * BLK + fTO * TOV + fPTS * PTS) %>%
  arrange(-DARKO_FPTS) %>%
  select(Player, DARKO_FPTS, PTS, everything())
```

